name: MapProtector
main: fr.cerasus.mapprotector.MapProtector
author: Dams4K
version: 1.0.0
commands:
  mapprotector:
    description: Enable or disable the map protector
    usage: /<command> <on|off>
    aliases:
      - mp
depend:
  - ServerMessager